### ISSUE TITLE
Output units of mag2flux

### ISSUE THREAD

**Issue by Bhavesh012** [tasoc/photometry#24]
## Query 

In the utility function, `photometry.utilities.mag2flux(mag, zp=20.60654144)`, what is the units of output flux? Is it in `e-/s` or in physical units `W/m^2`?

Also, what is the `zp` in the function? What it represents?

**Comment by rhandberg** [comment]
The `mag2flux` function outputs TESS magnitudes. It is a utility function we use for converting the flux measured by the TESS cameras (in e-/s) to TESS magnitudes. The `zp` is the zero-point in the conversion from flux to magnitudes and is derived from a fit to all the stars in a given Sector:
`Tmag = -2.5*log_10(flux) + zp`

This is described in the upcoming paper on the TASOC Photometry Pipeline (Handberg et al., in prep) and also in the latest data release notes: https://tasoc.dk/docs/release_notes/TASOC-0004-01/TASOC-0004-01.pdf

**Comment by Bhavesh012** [comment]
Any possible way of getting the output flux in `W/m^2` instead of having it in `e-/s`?
