### ISSUE TITLE
Add global star position changes (POS_CORR) added to output FITS

### ISSUE THREAD

**Issue by rhandberg** [tasoc/photometry#8]
We should add the changes to the target star position to the output FITS files.
- [x] Include POS_CORR columns in output FITS files
- [ ] TODO: Make sure TPF and FFI images have the same zero-point in POS_CORR

**Comment by benjaminpope** [comment]
Yes! Very important for eg GP regression - much better than raw centroids.

On Wed, Oct 24, 2018 at 11:37 AM Rasmus Handberg <notifications@github.com>
wrote:

> We should add the changes to the target star position to the output FITS
> files.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tasoc_photometry_issues_8&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=6mkPQ4afNcJ93wShdyTc7XJXxfFsIIkCCVLIUbB_zl8&s=aIPi7AKUuwC9fFtdetdMUmQYqjgJXLkzpcD95_BG230&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFvsFTm-2DOW3JADVCMSWWdhbw7da3wuycks5uoIkxgaJpZM4X4NLa&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=_gjp43gRuTt_LjqJbH0jcZo0ePCz10Y4KegSkx-Ha0A&m=6mkPQ4afNcJ93wShdyTc7XJXxfFsIIkCCVLIUbB_zl8&s=ItjmI-rxpTya6mFn0wPk4p4vOQ8H1GDqh25i9nQq0jI&e=>
> .
>
-- 
Dr Benjamin Pope
NASA Sagan Fellow
Center for Cosmology and Particle Physics
New York University
726 Broadway
New York, NY 10003
